type Person @embedded {
  FirstName: String
  LastName: String
  OutDateUnixTime: String
  RelationshipType: String
}

type PreviousId @embedded {
  IdValue: String
  IssuingShelter: String
  Type: String
}

type Attribute @embedded {
  AttributeName: String
  Publish: String
  InternalID: String
}

type Location @embedded {
  Tier1: String
  Tier2: String
  Tier3: String
}

type Microchip @embedded {
  Id: String
  Issuer: String
  ImplantUnixTime: String
}

type AdoptionFeeGroup @embedded {
  Id: String
  Name: String
  Price: String
  Discount: Int
  Tax: Int
}

type Video @embedded {
  VideoId: String
  EmbedUrl: String
  YoutubeUrl: String
  ThumbUrl: String
}

type Cat {
  Name: String
  ID: String
  InternalID: String
  LitterGroupId: String
  Type: String
  CurrentLocation: Location
  Sex: String
  Status: String
  InFoster: Boolean
  AssociatedPerson: Person
  CurrentWeightPounds: String
  Size: String
  Altered: String
  DOBUnixTime: Int
  Age: Int
  CoverPhoto: String
  Photos: [String]
  Videos: [Video]
  Breed: String
  Color: String
  Pattern: String
  AdoptionFeeGroup: AdoptionFeeGroup
  Description: String
  PreviousIds: [PreviousId]
  LastIntakeUnixTime: String
  LastUpdatedUnixTime: String
  Microchips: [Microchip]
  Attributes: [Attribute]
}

input PersonInput @embedded {
  FirstName: String
  LastName: String
  OutDateUnixTime: String
  RelationshipType: String
}

input PreviousIdInput @embedded {
  IdValue: String
  IssuingShelter: String
  Type: String
}

input AttributeInput @embedded {
  AttributeName: String
  Publish: String
  InternalID: String
}

input LocationInput @embedded {
  Tier1: String
  Tier2: String
  Tier3: String
}

input MicrochipInput @embedded {
  Id: String
  Issuer: String
  ImplantUnixTime: String
}

input AdoptionFeeGroupInput @embedded {
  Id: String
  Name: String
  Price: String
  Discount: Int
  Tax: Int
}

input VideoInput @embedded {
  VideoId: String
  EmbedUrl: String
  YoutubeUrl: String
  ThumbUrl: String
}

input CatInput {
  Name: String
  ID: String
  InternalID: String
  LitterGroupId: String
  Type: String
  CurrentLocation: LocationInput
  Sex: String
  Status: String
  InFoster: Boolean
  AssociatedPerson: PersonInput
  CurrentWeightPounds: String
  Size: String
  Altered: String
  DOBUnixTime: Int
  Age: Int
  CoverPhoto: String
  Photos: [String]
  Videos: [VideoInput]
  Breed: String
  Color: String
  Pattern: String
  AdoptionFeeGroup: AdoptionFeeGroupInput
  Description: String
  PreviousIds: [PreviousIdInput]
  LastIntakeUnixTime: String
  LastUpdatedUnixTime: String
  Microchips: [MicrochipInput]
  Attributes: [AttributeInput]
}

type Query {
  allCats: [Cat!]
  findCatByInternalId(InternalID: String): Cat
  findCatsByInternalIds(InternalIDs: [String]): [Cat]
    @resolver(name: "get_cat_internal_ids")
}

type Mutation {
  updateCatByInternalId(InternalID: String, updatedCat: CatInput): Cat
    @resolver(name: "update_cat_internal_id")
}

type Error @embedded {
  type: String
  cat: String
  content: String
}

type Event {
  since: Int
  startTime: Int
  endTime: Int
  tries: Int
  successes: Int
  errors: [Error]
}
